content_harvesting_task:
  description: >
    {topic}에 대한 최신 뉴스 기사를 수집합니다.

    단계:
    1. 검색 도구를 사용해 {topic} 관련 최신 뉴스를 검색합니다.
    2. 검색 결과에서 신뢰할 수 있는 출처의 URL을 식별합니다.

    3. **중요: 실제 기사 페이지만 선택하며, 주제 허브나 태그 목록 페이지는 제외해야 합니다.**
      다음과 같은 URL은 반드시 필터링해야 합니다:
      - 주제/태그/섹션 인덱스 페이지 (예: "/tag/", "/topic/", "/hub/", "/section/", "/category/" 포함)
      - 고유한 헤드라인이나 타임스탬프가 없는 페이지
      - 기사 본문 없이 다른 기사 링크만 나열된 페이지
      ✅ 허용되는 기사 URL:
      - 전체 기사 본문이 포함되어야 함
      - 명확한 헤드라인과 발행일이 있어야 함
      - 보통 `/2023/10/.../기사-제목` 또는 고유 스토리 ID를 포함함
      ❌ 허용되지 않는 URL 예시:
      - https://www.nytimes.com/topic/ 
      - https://apnews.com/hub
      - https://aljazeera.com/tag
      (이는 기사 모음 페이지이지 개별 기사가 아님)

    4. **허용된** 기사 URL에 대해서:
      - 스크랩 도구를 사용해 전체 기사 내용을 추출합니다.
      - 메타데이터(제목, 출처, 발행일, 전체 본문)를 추출합니다.

    5. 다음 조건으로 필터링을 적용합니다:
      - 200단어 이하 기사 제외
      - 48시간 이전 기사 제외 (특별히 관련성이 있는 경우 제외)
      - 스크랩 실패 또는 본문이 없는 페이지 제외

    6. 각 기사를 적절한 주제 카테고리(기술, 정치, 경제, 과학, 건강, 스포츠, 국제 등)로 분류합니다.

    7. 출처의 신뢰도와 콘텐츠 품질에 따라 신뢰도 점수(1-10)를 부여합니다.

    8. {topic}과의 적합성에 따라 관련도 점수(1-10)를 부여합니다.

  expected_output: >
    아래 형식을 따른 마크다운 문서로 수집된 기사들을 정리합니다:

    # 뉴스 기사 수집: {topic}

    **수집 요약**
    - 전체 기사 수: 
    - 필터링 후 기사 수:
    - 중복 제거 수:
    - 접근한 출처:
    - 사용한 검색 쿼리:
    - 검색 타임스탬프:

    ---

    ## 기사 1: [기사 제목]

    **출처:**
    **날짜:**
    **URL:**
    **카테고리:**
    **신뢰도 점수:**
    **관련도 점수:**


    ---
    [이 형식을 모든 기사에 적용...]

  agent: news_hunter_agent
  markdown: true
  output_file: output/content_harvest.md
  create_directory: true

summarization_task:
  description: >
    이전 작업에서 확보한 각 기사 URL을 요약합니다.

    스크랩 도구를 사용하여 기사 전체를 추출한 후, 각 기사에 대해 다음을 작성합니다:

    1. **헤드라인 요약** (280자 이하, 트윗 형식)
       - 핵심 본질을 소셜 미디어 형식으로 표현
       - 가장 뉴스 가치 있는 요소 강조
       - 주요 수치나 영향 지표 포함 시 효과적

    2. **간략 요약** (150–200자, 전문적 브리핑)
       - 바쁜 전문가와 뉴스 스키머를 위한 요약
       - 주요 사건과 즉각적 함의 포함
       - 주요 인물과 기본 맥락 언급

    3. **종합 요약** (500–700자, 전체 맥락)
       - 전체 맥락과 배경 설명
       - 다양한 관점과 전문가 의견 포함
       - 일반 독자도 이해할 수 있도록 기술적 개념 설명
       - 사건의 함의와 향후 전망 다룸

    모든 수준에서 저널리즘 톤, 객관성, 가독성을 유지합니다.
    원문 메타데이터를 기반으로 강조점을 설정합니다.

  expected_output: >
    아래 형식의 마크다운 문서로 다단계 요약을 작성합니다:

    # 뉴스 요약: {topic}

    **요약 보고서 개요**
    - 처리한 기사 수:
    - 요약 생성일:

    ---

    ## 기사 1: [원문 제목]

    **출처:**
    **날짜:**
    **원문 URL:**

    ### 📱 헤드라인 요약 (트윗 길이)
    [280자 요약...]

    ### 📋 간략 요약
    [150-200자 전문 브리핑...]

    ### 📖 종합 요약
    [500-700자 상세 요약...]

    **요약 품질 지표:**
    - 추천 독자:
    - 다룬 주요 주제:
    - 중요한 통계:
    - 주목할 만한 인용문:

    ---

    ## 기사 2: [다음 기사 제목] 

    [위와 동일한 형식...]

  agent: summarizer_agent
  markdown: true
  output_file: output/summary.md
  create_directory: true

final_report_assembly_task:
  description: >
    앞선 작업 결과를 종합하여 최종적으로 발행 가능한 전문 뉴스 브리핑을 마크다운 형식으로 작성합니다.

    조립 과정:
    1. 큐레이션 작업의 편집 계획에 따라 구조와 흐름을 구성합니다.
    2. 각 기사에 대해 편집 결정에 따라 적절한 요약 수준을 적용합니다.
    3. 큐레이션 계획에서 제공된 편집 전환부와 섹션 소개를 포함합니다.
    4. 당일 주요 발전을 요약하는 전문적인 오프닝을 작성합니다.
    5. 전체를 연결하고 미래를 전망하는 클로징 섹션을 만듭니다.
    6. 전체적으로 일관된 서식과 전문적인 프레젠테이션을 유지합니다.
    7. 적절한 출처 표기와 인용을 포함합니다.

    최종 보고서는 주요 언론사의 프리미엄 뉴스 브리핑처럼 읽혀야 합니다.

  expected_output: >
    최종 뉴스 브리핑 마크다운 문서 구조:

    # 일일 뉴스 브리핑: {topic}

    **날짜:** 
    **생성 시각:** 
    **다룬 기사:** 

    ## 요약 보고서

    [당일 가장 중요한 발전을 요약하고 전체 맥락을 설정하는 오프닝 단락]

    ---

    ## 🚨 오늘의 주요 기사

    ### [리드 기사 제목]

    [전체 맥락, 함의, 중요성을 담은 종합 요약]

    **출처:** [언론사] | **더 보기:** [링크](url)

    ---

    ## 📈 속보 및 주요 발전

    [이 섹션 소개문]

    ### [기사 제목]
    [간략 또는 종합 요약, 편집 결정에 따라]
    **출처:** [언론사] | **더 보기:** [링크](url)

    ---

    ## 💼 기술 및 혁신

    [이 섹션 소개문]

    ### [기사 제목]
    [편집 계획에 따른 적절한 요약]
    **출처:** [언론사] | **더 보기:** [링크](url)

    ---

    ## 🎯 편집자 분석

    **오늘의 핵심 주제:**
    - [주요 트렌드 또는 흐름]
    - [보조적 패턴 또는 발전]

    **의미:**
    [오늘 뉴스의 광범위한 함의 분석]

    **앞으로 주목할 점:**
    [오늘 뉴스 기반 향후 전망]

    ---

    ## 📚 추가 읽을거리

    **관련 기사:**
    - [간단 언급 + 링크]

    **배경 자료:**
    - [진행 중인 이슈 관련 중요 맥락 링크]

    ---

  agent: curator_agent
  markdown: true
  output_file: output/final_report.md
  create_directory: true
