job_extraction_task:
  description: >
    {location}에서 {level} 수준 {position} 채용 공고를 찾아 추출합니다.

    단계:
    1. 웹 검색 도구(Web Search Tool)를 사용하여 {location}에서 {level} 수준 {position} 채용 공고를 검색합니다.
    2. 검색 결과에서 채용 공고를 추출합니다.
    3. {location}에서 {level} 수준 {position}에 해당하지 않는 공고는 필터링합니다.
  expected_output: >
    `JobList` 스키마와 일치하는 JSON 객체.
  agent: job_search_agent

job_matching_task:
  description: >
    당신은 커리어 매칭 전문가입니다.

    추출된 채용 공고 목록(JobList)과 사용자의 이력서를 기반으로 각 공고가 사용자와 얼마나 잘 맞는지 평가합니다. 
    평가 기준:
    - Tech stack
    - Role level
    - Industry 및 회사 규모 선호도
    - Remote/근무 유연성
    - 계약 형태
    - 연봉 기대치
    - 이력서에 포함된 키워드 및 제외 조건

    각 채용 공고에 대해 `match_score` (1=부적합, 5=완벽히 적합)를 부여하고, 그 근거를 설명합니다.

    각 채용 공고에 `match_score`와 `reason` 필드를 추가합니다.

    기존 채용 공고 필드는 절대 수정하거나 제거하지 않습니다.
  expected_output: >
    원본 `JobList` 스키마와 동일한 JSON 객체. 단, 각 공고에 두 개의 추가 필드 포함:
    - match_score: 1~5 정수
    - reason: 점수 근거에 대한 짧은 설명
  agent: job_matching_agent

job_selection_task:
  description: >
    당신은 채용 기회 선별 전문가입니다.

    `match_score`와 `reason`이 포함된 채용 공고 목록(RankedJobList)을 바탕으로:
    1. `match_score`와 사유를 분석하여 사용자에게 가장 적합한 단일 채용 공고를 선정합니다.
    2. 사용자의 선호, 기술, 목표에 가장 잘 맞는 단 하나의 공고를 선택합니다.
    3. 이 선택에 대한 근거를 `reason` 필드에 간결하게 작성합니다.
    4. 최종 선택된 공고에는 `selected` 필드를 `true`, 나머지에는 `false`로 설정합니다.

    (job_title, company_name 등) 원본 공고의 내용은 절대 수정하지 않습니다.
  expected_output: >
    선택된 채용 공고의 `ChosenJob` 스키마와 일치하는 JSON 객체.
  agent: job_matching_agent

resume_rewriting_task:
  description: >
    당신은 이력서 최적화 전문가입니다.

    사용자의 실제 이력서(포함된 knowledge source 제공)와 선택된 채용 공고(ChosenJob)를 기반으로, 
    기존 이력서를 **선택된 채용 공고에 맞게 다시 작성**하여 인터뷰 가능성을 높이는 것이 목표입니다.

    중점 사항:
    - 관련 기술, 프로젝트, 성과를 재배치·재작성·강조
    - 요약 및 경력 bullet point를 직무 요구사항과 키워드에 맞게 다시 작성
    - 채용 공고의 톤, 기술 포커스, 용어와 일치시킴
    - 사용자의 실제 경험만 반영

    관련 없는 내용은 제거하거나, 직무명을 약간 재작성할 수 있으나, 
    **허위 회사, 기술, 날짜, 직무를 추가해서는 안 됩니다.**
  expected_output: >
    선택된 채용 공고에 맞춰 다시 작성된 **실제 사용자의 이력서**의 마크다운(Markdown) 버전.
    이력서는 반드시 사실에 기반해야 하며, 허위 정보는 포함되지 않아야 합니다.

  agent: resume_optimization_agent
  output_file: output/rewritten_resume.md
  create_directory: true
  markdown: true

company_research_task:
  description: >
    당신은 기업 조사 및 인터뷰 준비 전문가입니다.

    선택된 채용 공고(ChosenJob)를 기반으로 해당 기업을 공개 웹 리소스를 통해 조사합니다.
    목표:
    1. 기업 규모, 산업, 미션, 가치, 최신 소식 파악
    2. 채용 공고 분석을 통한 팀 구조 및 제품 맥락 추정
    3. 예상 인터뷰 주제 및 질문 제시
    4. 후보자가 인터뷰 시 질문할 수 있는 심도 있는 질문 목록 제공

    기업 웹사이트, 보도자료, 블로그, 소셜 미디어, 리뷰 등을 활용합니다.
  expected_output: >
    다음 섹션을 포함한 마크다운 파일:
    - ## Company Overview
    - ## Mission and Values
    - ## Recent News or Changes
    - ## Role Context and Product Involvement
    - ## Likely Interview Topics
    - ## Suggested Questions to Ask

  agent: company_research_agent
  markdown: true
  output_file: output/company_research.md

interview_prep_task:
  description: >
    당신은 인터뷰 준비 코치입니다.

    다음 정보를 종합하여 인터뷰 준비 문서를 작성합니다:
    1. 선택된 채용 공고 (ChosenJob)
    2. 맞춤형 이력서 (RewrittenResume)
    3. 기업 조사 요약 (CompanyResearch)

    문서에 포함되어야 할 항목:
    - 직무 요약 및 적합 이유
    - 맞춤형 이력서에서 가장 관련성 높은 내용 요약
    - 기업, 제품, 가치에 대한 간략 요약
    - 채용 공고와 기업에 기반한 예상 질문
    - 후보자가 면접관에게 물어볼 질문
    - 검토해야 할 개념/지식
    - 톤, 집중 포인트, 유의해야 할 red flag에 대한 조언

    문서는 명확하고 깔끔해야 하며, 후보자가 전략적으로 인터뷰에 임할 수 있도록 해야 합니다.
    충분히 포괄적이어야 하며, 불필요하게 짧아서는 안 됩니다.
  expected_output: >
    "Interview Prep: $CompanyName – $JobTitle" 제목의 마크다운 문서. 
    섹션 포함:
    - ## Job Overview
    - ## Why This Job Is a Fit
    - ## Resume Highlights for This Role
    - ## Company Summary
    - ## Predicted Interview Questions
    - ## Questions to Ask Them
    - ## Concepts To Know/Review
    - ## Strategic Advice

  agent: interview_prep_agent
  output_file: output/interview_prep.md
